CREATE OR REPLACE TABLE PRODUCTS (
  PRODUCT_ID STRING,
  PRODUCT_NAME STRING,
  PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE OFFERS (
  OFFER_CODE STRING,
  OFFER_TYPE STRING,
  OFFER_VALUE NUMBER(10,2)
);

CREATE OR REPLACE TABLE SALES (
  INVOICE_ID STRING,
  BILL_DATE DATE,
  SUBTOTAL NUMBER(10,2),
  DISCOUNT NUMBER(10,2),
  FINAL_AMOUNT NUMBER(10,2)
);

INSERT INTO PRODUCTS VALUES
('P1','Laptop',60000),
('P2','Mobile',30000),
('P3','Headphones',3000);

INSERT INTO OFFERS VALUES
('FLAT500','FLAT',500),
('DISC10','PERCENT',10);
